### ISSUE TITLE
Missing Sherlock Annotation

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#105]
Seen a few objects with missing Sherlock annotations this week.  Something is aborting too early?

E.g.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1093623681430216200/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1135326161442149100/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1150755801394805900/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1122537661072333800/

**Comment by genghisken** [comment]
I'm sure you know this already, but here's the ATLAS error log from the sherlock calls:

```
14736 transient sources requiring a classification remain
  now classifying the next 5000 transient sources
BATCH SIZE = 5000
MINI BATCH SIZE = 51 x 100
START CROSSMATCH
FINISH CROSSMATCH/START RANKING: 93
FINISH RANKING/START UPDATING TRANSIENT DB: 6
UPDATING TRANSIENTS DATABASE WITH RESULTS
DELETING OLD RESULTS
FINISHED DELETING OLD RESULTS/ADDING TO CROSSMATCHES: 2
Starting to insert 23498 rows into sherlock_crossmatches
^[[1A^[[2K23498 / 23498 rows inserted into sherlock_crossmatches
FINISHED ADDING TO CROSSMATCHES/UPDATING CLASSIFICATIONS IN TRANSIENT TABLE: 4
FINISHED UPDATING CLASSIFICATIONS IN TRANSIENT TABLE/UPDATING sherlock_classifications TABLE: 0
Starting to insert 5000 rows into sherlock_classifications
^[[1A^[[2K5000 / 5000 rows inserted into sherlock_classifications
FINISHED UPDATING sherlock_classifications TABLE: 1
FINISH UPDATING TRANSIENT DB/START ANNOTATING TRANSIENT DB: 8
Traceback (most recent call last):
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/bin/sherlock", line 11, in <module>
    sys.exit(main())
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/cl_utils.py", line 171, in main
    classifier.classify()
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/transient_classifier.py", line 449, in classify
    self.updatePeakMags)
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/transient_classifier.py", line 1435, in update_classification_annotations_and_summaries
    match=row, updatePeakMagnitudes=updatePeakMagnitudes)
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/transient_classifier.py", line 1944, in generate_match_annotation
    annotation = "The transient is %(classificationReliability)s with <em>%(objectId)s</em>; %(best_mag_filter)s%(best_mag)smag %(objectType)s found in the %(catalogueString)s. It's located %(location)s.%(absMag)s" % locals()
KeyError: 'classificationReliability'
```

**Comment by thespacedoctor** [comment]
This is the same error as seen on Lasair. Working on this now

**Comment by thespacedoctor** [comment]
all fixed
