### ISSUE TITLE
Sherlock errors on Pan-STARRS

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#115]
PS1 has started to report errors as of the date on the logfile below...

```
pstc::db0 { /db0/tc_logs/ps13pi }-> cat sherlock_20200719_0341.log 
58124 transient sources requiring a classification remain
  now classifying the next 5000 transient sources
BATCH SIZE = 5000
MINI BATCH SIZE = 51 x 100
START CROSSMATCH
FINISH CROSSMATCH/START RANKING: 107
FINISH RANKING/START UPDATING TRANSIENT DB: 5
UPDATING TRANSIENTS DATABASE WITH RESULTS
DELETING OLD RESULTS
FINISHED DELETING OLD RESULTS/ADDING TO CROSSMATCHES: 1
.
<snip>
.
23124 transient sources requiring a classification remain
  now classifying the next 5000 transient sources
BATCH SIZE = 5000
MINI BATCH SIZE = 51 x 100
START CROSSMATCH
FINISH CROSSMATCH/START RANKING: 60
FINISH RANKING/START UPDATING TRANSIENT DB: 6
UPDATING TRANSIENTS DATABASE WITH RESULTS
DELETING OLD RESULTS
FINISHED DELETING OLD RESULTS/ADDING TO CROSSMATCHES: 0
19726 / 19726 rows inserted into sherlock_crossmatches
FINISHED ADDING TO CROSSMATCHES/UPDATING CLASSIFICATIONS IN TRANSIENT TABLE: 4
FINISHED UPDATING CLASSIFICATIONS IN TRANSIENT TABLE/UPDATING sherlock_classifications TABLE: 0
5000 / 5000 rows inserted into sherlock_classifications
FINISHED UPDATING sherlock_classifications TABLE: 3
FINISH UPDATING TRANSIENT DB/START ANNOTATING TRANSIENT DB: 7
Traceback (most recent call last):
  File "/usr/local/swtools/python/pstc/anaconda3/envs/sherlock_panstarrs37/bin/sherlock", line 8, in <module>
    sys.exit(main())
  File "/usr/local/swtools/python/pstc/anaconda3/envs/sherlock_panstarrs37/lib/python3.7/site-packages/sherlock/cl_utils.py", line 208, in main
    classifier.classify()
  File "/usr/local/swtools/python/pstc/anaconda3/envs/sherlock_panstarrs37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 480, in classify
    self.updatePeakMags)
  File "/usr/local/swtools/python/pstc/anaconda3/envs/sherlock_panstarrs37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 1446, in update_classification_annotations_and_summaries
    match=row, updatePeakMagnitudes=updatePeakMagnitudes)
  File "/usr/local/swtools/python/pstc/anaconda3/envs/sherlock_panstarrs37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 1879, in generate_match_annotation
    e = float(match["eastSeparationArcsec"])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by genghisken** [comment]
FYI I found 182 rows in sherlock_crossmatches with eastSeparationArcsec set to NULL.  All datestamps where 19th July.  So I deleted all 182 rows.  No idea what happened to the INSERT statements, because it seemed to be inserting random junk into this table (e.g. transient_object_id was junk or NULL in most cases).

```
mysql> select transient_object_id, dateLastModified from sherlock_crossmatches where eastSeparationArcsec is null;
+---------------------+---------------------+
| transient_object_id | dateLastModified    |
+---------------------+---------------------+
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1221834840174643100 | 2020-07-19 03:55:47 |
|                  46 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|  122314210018383440 | 2020-07-19 03:55:47 |
|                  37 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1160646540155237600 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   3 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                   1 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                 307 | 2020-07-19 03:55:47 |
|                  10 | 2020-07-19 03:55:47 |
|             1204446 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1215945121003030300 | 2020-07-19 03:55:47 |
|    1222255881045344 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   1 | 2020-07-19 03:55:47 |
| 1223552571045927500 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|   12303098410645002 | 2020-07-19 03:55:47 |
|                 303 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                 329 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1220922261013639600 | 2020-07-19 03:55:47 |
| 1221521351053651500 | 2020-07-19 03:55:47 |
| 1222401211072612900 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                 338 | 2020-07-19 03:55:47 |
| 1201810261072742100 | 2020-07-19 03:55:47 |
|      10035565012913 | 2020-07-19 03:55:47 |
| 1224039981023237100 | 2020-07-19 03:55:47 |
| 1224242881061216400 | 2020-07-19 03:55:47 |
| 1224948521305849300 | 2020-07-19 03:55:47 |
|                   1 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   4 | 2020-07-19 03:55:47 |
|                  19 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                  80 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                 340 | 2020-07-19 03:55:47 |
|                  17 | 2020-07-19 03:55:47 |
|                  47 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                 334 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1224550461032811200 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   1 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1221834840174643100 | 2020-07-19 03:55:47 |
|                  46 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|  122314210018383440 | 2020-07-19 03:55:47 |
|                  37 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1160646540155237600 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   3 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                   1 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                 307 | 2020-07-19 03:55:47 |
|                  10 | 2020-07-19 03:55:47 |
|             1204446 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1215945121003030300 | 2020-07-19 03:55:47 |
|    1222255881045344 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   1 | 2020-07-19 03:55:47 |
| 1223552571045927500 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|   12303098410645002 | 2020-07-19 03:55:47 |
|                 303 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                 329 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1220922261013639600 | 2020-07-19 03:55:47 |
| 1221521351053651500 | 2020-07-19 03:55:47 |
| 1222401211072612900 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                 338 | 2020-07-19 03:55:47 |
| 1201810261072742100 | 2020-07-19 03:55:47 |
|      10035565012913 | 2020-07-19 03:55:47 |
| 1224039981023237100 | 2020-07-19 03:55:47 |
| 1224242881061216400 | 2020-07-19 03:55:47 |
| 1224948521305849300 | 2020-07-19 03:55:47 |
|                   1 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   4 | 2020-07-19 03:55:47 |
|                  19 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                  80 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                 340 | 2020-07-19 03:55:47 |
|                  17 | 2020-07-19 03:55:47 |
|                  47 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                 334 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
| 1224550461032811200 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                   1 | 2020-07-19 03:55:47 |
|                   0 | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
|                NULL | 2020-07-19 03:55:47 |
+---------------------+---------------------+
182 rows in set (15.48 sec)
```

**Comment by thespacedoctor** [comment]
Is this fixed?
