### ISSUE TITLE
SDSS name conversion error

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#137]
Getting some skipped annotations because the code falls over when it tries to convert SDSS objects into names.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1122646551085257700/

```
* 08:35:34 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
Traceback (most recent call last):
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/bin/sherlock", line 8, in <module>
    sys.exit(main())
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/sherlock/cl_utils.py", line 208, in main
    classifier.classify()
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 493, in classify
    self.updatePeakMags)
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 1545, in update_classification_annotations_and_summaries
    match=row, updatePeakMagnitudes=updatePeakMagnitudes)
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 1948, in generate_match_annotation
    betterName = "SDSS J" + ra[0:9] + dec[0:9]
TypeError: 'int' object is not subscriptable
```

**Comment by genghisken** [comment]
Latest error today - repeat of the above:
```
cat sherlock_20210720_0934.log 
165 transient sources requiring a classification remain
  now classifying the next 165 transient sources
BATCH SIZE = 165
MINI BATCH SIZE = 2 x 100
START CROSSMATCH
FINISH CROSSMATCH/START RANKING: 9
FINISH RANKING/START UPDATING TRANSIENT DB: 0
UPDATING TRANSIENTS DATABASE WITH RESULTS
DELETING OLD RESULTS
FINISHED DELETING OLD RESULTS/ADDING TO CROSSMATCHES: 0
566 / 566 rows inserted into sherlock_crossmatches
FINISHED ADDING TO CROSSMATCHES/UPDATING CLASSIFICATIONS IN TRANSIENT TABLE: 0
FINISHED UPDATING CLASSIFICATIONS IN TRANSIENT TABLE/UPDATING sherlock_classifications TABLE: 0
165 / 165 rows inserted into sherlock_classifications
FINISHED UPDATING sherlock_classifications TABLE: 0
FINISH UPDATING TRANSIENT DB/START ANNOTATING TRANSIENT DB: 1
* 09:35:03 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
Traceback (most recent call last):
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/bin/sherlock", line 8, in <module>
    sys.exit(main())
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/sherlock/cl_utils.py", line 208, in main
    classifier.classify()
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 493, in classify
    self.updatePeakMags)
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 1545, in update_classification_annotations_and_summaries
    match=row, updatePeakMagnitudes=updatePeakMagnitudes)
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/sherlock/transient_classifier.py", line 1948, in generate_match_annotation
    betterName = "SDSS J" + ra[0:9] + dec[0:9]
TypeError: 'int' object is not subscriptable
```

**Comment by genghisken** [comment]
The problem began shortly after 14:00 on 7th July:

```
atls::db4 { /db4/tc_logs/atlas4 }-> grep ERROR sherlock_202107*.log
sherlock_20210707_1400.log:* 14:04:20 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210708_0244.log:* 02:48:16 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210708_0525.log:* 05:25:31 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210708_0835.log:* 08:35:34 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210708_1115.log:* 11:17:32 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210708_1750.log:* 17:54:22 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210708_2321.log:* 23:23:29 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210709_0815.log:* 08:15:28 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210709_0925.log:* 09:25:40 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210709_1236.log:* 12:39:09 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210709_1726.log:* 17:29:48 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210709_2249.log:* 22:52:19 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210710_0817.log:* 08:17:41 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210710_1136.log:* 11:39:18 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210710_1720.log:* 17:24:46 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210710_2249.log:* 22:50:43 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210711_0815.log:* 08:15:32 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210711_0934.log:* 09:35:28 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210711_1302.log:* 13:06:29 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210711_1839.log:* 18:42:38 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210711_2218.log:* 22:19:23 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210712_0810.log:* 08:10:21 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210712_0914.log:* 09:14:23 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210712_1016.log:* 10:17:07 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210712_1137.log:* 11:37:38 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210712_1617.log:* 16:20:08 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210712_1909.log:* 19:10:23 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210713_0816.log:* 08:17:02 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210713_0935.log:* 09:36:04 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210713_1309.log:* 13:11:41 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210713_2011.log:* 20:14:52 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210714_0625.log:* 06:25:57 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210714_0820.log:* 08:21:02 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210714_0947.log:* 09:48:01 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210714_1421.log:* 14:24:25 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210714_2035.log:* 20:38:48 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210715_0058.log:* 00:59:32 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210715_0814.log:* 08:15:23 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210715_0920.log:* 09:20:58 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210715_1029.log:* 10:30:20 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210715_1330.log:* 13:32:17 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210715_2017.log:* 20:21:31 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210716_0203.log:* 02:04:21 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210716_0813.log:* 08:13:54 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210716_0924.log:* 09:25:17 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210716_1041.log:* 10:42:03 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210716_1433.log:* 14:35:54 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210716_1829.log:* 18:32:08 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210717_0802.log:* 08:03:24 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210717_0950.log:* 09:51:32 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210717_1327.log:* 13:30:40 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210717_2034.log:* 20:38:13 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210718_0309.log:* 03:10:13 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210718_0825.log:* 08:25:45 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210718_0939.log:* 09:40:44 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210718_1415.log:* 14:19:34 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210718_2028.log:* 20:32:18 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210719_0056.log:* 00:56:53 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210719_0814.log:* 08:14:39 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210719_0939.log:* 09:40:13 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210719_1309.log:* 13:13:01 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210719_1859.log:* 19:03:59 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210719_2340.log:* 23:41:22 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210720_0809.log:* 08:10:12 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210720_0934.log:* 09:35:03 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
sherlock_20210720_1244.log:* 12:47:03 - ERROR: /usr/local/swtools/python/atls/anaconda3/envs/sherlock37/lib/python3.7/site-packages/astrocalc/coords/unit_conversion.py:dec_decimal_to_sexegesimal:443 > DEC must be between -90 - 90 degrees
```

**Comment by thespacedoctor** [comment]
this was resolved 2 weeks ago
