### ISSUE TITLE
Multiprocessing cPickle error in Sherlock using annaconda/RHEL 6

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#36]
When I try to run sherlock, I get the following error:

```
10774 transient sources requiring a classification remain
  now classifying the next 250 transient sources
Traceback (most recent call last):
  File "/home/atls/anaconda2/bin/sherlock", line 11, in <module>
    sys.exit(main())
  File "/home/atls/anaconda2/lib/python2.7/site-packages/sherlock/cl_utils.py", line 170, in main
    classifier.classify()
  File "/home/atls/anaconda2/lib/python2.7/site-packages/sherlock/transient_classifier.py", line 289, in classify
    inputArray=range(len(theseBatches)), colMaps=colMaps)
  File "/home/atls/anaconda2/lib/python2.7/site-packages/fundamentals/fmultiprocess.py", line 72, in fmultiprocess
    resultArray = p.map(mapfunc, inputArray)
  File "/home/atls/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/atls/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

**Comment by thespacedoctor** [comment]
Resolved this issue.
