### ISSUE TITLE
Sherlock cPickle error (called from older database)

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#48]
Another error from sherlock when being called from PS1.

```
477455 transient sources requiring a classification remain
  now classifying the next 500 transient sources
Traceback (most recent call last):
  File "/home/atls/anaconda2/bin/sherlock", line 11, in <module>
    load_entry_point('qub-sherlock', 'console_scripts', 'sherlock')()
  File "/home/atls/git_repos/sherlock/sherlock/cl_utils.py", line 170, in main
    classifier.classify()
  File "/home/atls/git_repos/sherlock/sherlock/transient_classifier.py", line 289, in classify
    inputArray=range(len(theseBatches)), colMaps=colMaps)
  File "/home/atls/anaconda2/lib/python2.7/site-packages/fundamentals/fmultiprocess.py", line 72, in fmultiprocess
    resultArray = p.map(mapfunc, inputArray)
  File "/home/atls/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/atls/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed

```

**Comment by thespacedoctor** [comment]
These guys again!

/home/atls/anaconda2/lib/python2.7/site-packages/fundamentals/multiprocess.py
/home/atls/anaconda2/lib/python2.7/site-packages/fundamentals/multiprocess.pyc

I've removed them - try again ;)
