### ISSUE TITLE
update milliquas to version 5.2

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/sherlock#53]
The milliquas catalogue installed in the sherlock catalogues database is currently v4.8. v5.2 includes QSOs from SDSS DR14 and claims to be the last update to the catalogue for some time.

**Comment by thespacedoctor** [comment]
Milliquas is now updated to v5.2 in the sherlock catalogues database.

**Comment by genghisken** [comment]
Great that v5.2 is now installed. But we now need to update the PS1 and ATLAS algorithm config files to refer to the new catalog!  Otherwise...

`363640 transient sources requiring a classification remain
  now classifying the next 1219 transient sources
BATCH SIZE = 1218
MINI BATCH SIZE = 42 x 29
START CROSSMATCH
Traceback (most recent call last):
  File "/home/atls/anaconda2/bin/sherlock", line 11, in <module>
    load_entry_point('qub-sherlock', 'console_scripts', 'sherlock')()
  File "/home/atls/git_repos/sherlock/sherlock/cl_utils.py", line 170, in main
    classifier.classify()
  File "/home/atls/git_repos/sherlock/sherlock/transient_classifier.py", line 353, in classify
    inputArray=range(len(theseBatches)), poolSize=None, colMaps=colMaps)
  File "/home/atls/git_repos/fundamentals/fundamentals/fmultiprocess.py", line 71, in fmultiprocess
    resultArray = resultArray.get(timeout=timeout)
  File "/home/atls/anaconda2/lib/python2.7/site-packages/multiprocess/pool.py", line 567, in get
    raise self._value
pymysql.err.ProgrammingError: (1146, u"Table 'crossmatch_catalogues.tcs_view_agn_milliquas_v4_8' doesn't exist")`

**Comment by thespacedoctor** [comment]
I had updated the sherlock_atlas4_all algorithm ... you just need to switch
it out in whatever other settings files you use. All you need to do is
change the version number.
