### ISSUE TITLE
Database error when running full sherlock search on individual object

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#77]
This is probably a config error on my part, but when running a simple RA/Dec check with a full NED search, I get the following output and error.

```
/usr/local/swtools/python/atls/anaconda3/envs/sherlock/bin/sherlock match -- 21.79395 -32.23454 ~/.config/sherlock/sherlock_atlas4_all.yaml
requesting metadata from NED for 50000 galaxies (batch 1)
  278 / 278 (100.0%) URLs downloaded
results returned from ned -- starting to add to database
49996 / 49996 rows inserted into tcs_cat_ned_stream
Starting to insert 50000 rows into tcs_cat_ned_stream
Traceback (most recent call last):
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/bin/sherlock", line 11, in <module>
    load_entry_point('qub-sherlock==1.6.3', 'console_scripts', 'sherlock')()
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/cl_utils.py", line 169, in main
    classifier.classify()
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/transient_classifier.py", line 326, in classify
    transientsMetadataList=transientsMetadataList
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/transient_classifier.py", line 521, in _update_ned_stream
    stream.ingest()
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/imports/ned.py", line 164, in ingest
    self._download_ned_source_metadata()
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/imports/ned.py", line 327, in _download_ned_source_metadata
    thisCount)
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/imports/ned.py", line 448, in _do_ned_namesearch_queries_and_add_resulting_metadata_to_database
    createStatement="""SET SESSION sql_mode="";"""
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/imports/_base_importer.py", line 189, in add_data_to_database_table
    self._add_htmids_to_database_table()
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/sherlock/imports/_base_importer.py", line 235, in _add_htmids_to_database_table
    primaryIdColumnName=self.primaryIdColumnName
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/HMpTy/mysql/add_htm_ids_to_mysql_database_table.py", line 311, in add_htm_ids_to_mysql_database_table
    dateCreated=False
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/fundamentals/mysql/insert_list_of_dictionaries_into_database_tables.py", line 143, in insert_list_of_dictionaries_into_database_tables
    dateCreated=dateCreated
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/fundamentals/fmultiprocess.py", line 77, in fmultiprocess
    resultArray = resultArray.get(timeout=timeout)
  File "/usr/local/swtools/python/atls/anaconda3/envs/sherlock/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
    raise self._value
pymysql.err.OperationalError: (2006, "MySQL server has gone away (error(32, 'Broken pipe'))")
```

**Comment by thespacedoctor** [comment]
I think this was an issue with mutliprocessing and pymysql not being threadsafe for connections. Once I gave one connection per process (in fundamentals package) the problem went away.
