### ISSUE TITLE
Unable to call sherlock after upgrade on Pan-STARRS machines

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#92]
Trying to call sherlock after upgrading it on the Pan-STARRS machines.  I tried the usual removal of multiprocessing*, but to no avail.  I'll not be rolling out to ATLAS until this is resolved!

```
sherlock dbmatch -AN --update -s /home/pstc/.config/sherlock/sherlock_ps13pi_all.yaml 
Traceback (most recent call last):
  File "/usr/local/swtools/python/pstc/anaconda3/envs/sherlock_panstarrs/bin/sherlock", line 10, in <module>
    sys.exit(main())
  File "/usr/local/swtools/python/pstc/anaconda3/envs/sherlock_panstarrs/lib/python2.7/site-packages/sherlock/cl_utils.py", line 167, in main
    updatePeakMags=updatePeakMags
  File "/usr/local/swtools/python/pstc/anaconda3/envs/sherlock_panstarrs/lib/python2.7/site-packages/sherlock/transient_classifier.py", line 172, in __init__
    settings=self.settings
TypeError: 'module' object is not callable
```

**Comment by genghisken** [comment]
False alarm!  I upgraded the wrong "sherlock".  Should be qub-sherlock of course.
